### ISSUE TITLE
make 后出错了

### ISSUE THREAD

**Issue by UltramanNOAS** [SmallPond/MyNES#1]
![Snipaste_2022-03-12_21-13-45](https://user-images.githubusercontent.com/63765449/158019345-f84fcc96-594d-4f38-8119-8e075d2b97f8.png)
![Snipaste_2022-03-12_21-13-55](https://user-images.githubusercontent.com/63765449/158019346-667d774c-475d-44aa-a776-dbb8ae8ddac6.png)

**Comment by SmallPond** [comment]
> ![Snipaste_2022-03-12_21-13-45](https://user-images.githubusercontent.com/63765449/158019345-f84fcc96-594d-4f38-8119-8e075d2b97f8.png)
> ![Snipaste_2022-03-12_21-13-55](https://user-images.githubusercontent.com/63765449/158019346-667d774c-475d-44aa-a776-dbb8ae8ddac6.png)
> 
> 

报错是sfml库没有找到，你是否按sfml官方文档安装库了呢？

**Comment by UltramanNOAS** [comment]
老哥，这个sfml怎么配置呢，我把makefile的文件里的路径修改到了我下载的库中了

**Comment by SmallPond** [comment]
> 老哥，这个sfml怎么配置呢，我把makefile的文件里的路径修改到了我下载的库中了

在readme中链接了官方文档。 你这是在windows下跑的吧？我没有试过在Windows下跑。  不过你的错误输出是说库不兼容，应该是版本装错了。 你装的Linux SFML库还是windows库？
